name = "events-api-tampa-dev"
main = "src/index.ts"
send_metrics = true

compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

kv_namespaces = [
  { binding = "kv", id = "791983cf109c43eaa21ff4f3406de811" }
]

[build]
command="npm run handlebars"
watch_dir="views/"

[env.pr]
name = "events-api-pr"

[env.production]
name = "events-api-tampa-dev"
kv_namespaces = [
  { binding = "kv", id = "791983cf109c43eaa21ff4f3406de811" }
]